### ISSUE TITLE
Possible issue when running mpicc ga.h ga.c

### ISSUE THREAD

**Issue by pczcanda** [JWCook/MPI_Distributed_Genetic_Algorithm#1]
Hi,

I'm fairly new to C code and I am trying to get it to run. I have now installed open mpi and am trying to get the program to run however when running `mpicc ga.h ga.c` I get the following error:

```
Undefined symbols for architecture x86_64:
  "_fitness", referenced from:
      _main in ga-80dffb.o
  "_init_population", referenced from:
      _main in ga-80dffb.o
  "_mt_probability", referenced from:
      _crossover in ga-80dffb.o
      _mutation in ga-80dffb.o
  "_mt_rand_int", referenced from:
      _mutation in ga-80dffb.o
  "_mt_rand_real", referenced from:
      _selection in ga-80dffb.o
  "_report_all", referenced from:
      _main in ga-80dffb.o
  "_report_fittest", referenced from:
      _main in ga-80dffb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Could you provide some guidance as to how this could be resolved, please?

Thank you

**Comment by JWCook** [comment]
Good question! This code was originally for an undergrad project about 12 years ago, so it's likely that OpenMPI has had some significant changes since then. I'll add this to my todo list and see if I can get this thing running again.

**Comment by JWCook** [comment]
Oh, nevermind, I see. When you run `mpicc ga.h ga.c`, the error message is saying it can't compile because it's missing additional headers that need to be linked.

You need to run `make all` to compile. See the [Makefile](https://github.com/JWCook/MPI_Distributed_Genetic_Algorithm/blob/master/Makefile) for the individual compile commands it runs. I updated the Readme to clarify. I was able to compile this again with OpenMPI 4.0.3 / GCC 9.3.0.

Let me know if that works for you.
